Add factsheet message definition
clearpathrobotics/vda5050_msgs pull request #1
Opened 2022-08-19 14:36 UTC by FlorGrosso

This PR adds the ROS2 message definitions required to support factsheet requests, as defined on the [schema](https://github.com/VDA5050/VDA5050/blob/main/json_schemas/factsheet.schema).

2022-08-19 14:39 UTC, FlorGrosso commented on vda5050_msgs/msg/Envelope3D.msg
> +int32 description
The schema defines this as:

```
"description": {
  "type": "integer",
  "description": "free text: description of envelope curve set"
}
```

Which seems to correspond better with a string type.

2022-08-19 14:41 UTC, FlorGrosso commented on vda5050_msgs/msg/TypeSpecification.msg
> +string PHYSICAL_LINDE_GUIDED = "PHYSICAL_LINDE_GUIDED"
'PHYSICAL_LINE_GUIDED' would make more sense here but the [schema](https://github.com/VDA5050/VDA5050/blob/main/json_schemas/factsheet.schema#L112) indicates 'PHYSICAL_LINDE_GUIDED'

2022-08-19 14:43 UTC, FlorGrosso commented on vda5050_msgs/msg/MaxArrayLens.msg
> +int32 order_nodes                   # Maximum number of nodes per order processable by the AGV
The [schema](https://github.com/VDA5050/VDA5050/blob/main/json_schemas/factsheet.schema#L221) defines the fields on this message as `order.nodes` for example. I've used snake case here but we could also create nested fields for consistency if needed.

2022-08-19 17:38 UTC, nwn-cpr requested changes
Generally looks good, with a few minor notes.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/CMakeLists.txt
> +    "msg/AGVGeometry.msg"
Please move the `"msg/AGVPosition.msg"` line from above to be grouped with these.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/AGVAction.msg
> +string[] action_scopes                          # Allowed scopes for using this action-type
Should `action_scopes` be an `ActionScope[]` rather than untyped strings? Or alternatively, could the constants defined in `ActionScope.msg` be moved into this file? I can't quite tell what the existing treatment for enums is.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/Envelope3D.msg
> +int32 description
You're right, this does seem wrong. The [text spec](https://github.com/VDA5050/VDA5050/blob/main/VDA5050_EN.md#user-content-agvgeometry) lists it as a string, which also agrees with the Envelope2D message. I think we can safely say that it should be a string.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/MaxArrayLens.msg
> +int32 order_nodes                   # Maximum number of nodes per order processable by the AGV
I think snake case is fine here.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/MaxArrayLens.msg
> +int32 info_references               # Maximum number of info references sent by the AGV for each information
The [text spec](https://github.com/VDA5050/VDA5050/blob/main/VDA5050_EN.md#protocollimits) defines all these (and most of the fields of `maxStringLens`) as uint32. This is inexpressible in JSON, but we should probably use `uint32` here as well.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/TypeSpecification.msg
> +string PHYSICAL_LINDE_GUIDED = "PHYSICAL_LINDE_GUIDED"
Hmm, again the text spec doesn't align with the schema. Let's follow the spec here and not propagate the error.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/Factsheet.msg
> +                                        # (but not necessarily received) message.
Spec calls for uint32.

2022-08-19 17:38 UTC, nwn-cpr commented on vda5050_msgs/msg/Factsheet.msg
> +int32 localization_parameters           # Detailed specification of localization
Just noting here that this is listed as a JSON-object in the [spec](https://github.com/VDA5050/VDA5050/blob/main/VDA5050_EN.md#6161-factsheet-json-strcture), but isn't actually defined anywhere. We can follow the schema and leave this as an integer, even if it's just a placeholder value for now.

2022-08-22 20:26 UTC, FlorGrosso commented on vda5050_msgs/msg/Envelope3D.msg
> +int32 description
Sounds good, yes.

2022-08-22 20:26 UTC, FlorGrosso commented on vda5050_msgs/msg/TypeSpecification.msg
> +string PHYSICAL_LINDE_GUIDED = "PHYSICAL_LINDE_GUIDED"
+1

2022-08-22 20:29 UTC, FlorGrosso commented on vda5050_msgs/msg/AGVAction.msg
> +string[] action_scopes                          # Allowed scopes for using this action-type
Sounds good, I'll do the later. I've been following the structure of the messages already defined on the package, which define enums as strings and add a list of the possible values on the same file (e.g. [blocking types](https://github.com/ipa320/vda5050_msgs/blob/master/msg/Action.msg#L31)).

2022-08-22 20:30 UTC, FlorGrosso commented on vda5050_msgs/msg/MaxArrayLens.msg
> +int32 info_references               # Maximum number of info references sent by the AGV for each information
Sounds good, I'll update these to match the text spec (as well as other cases that I've identified).

2022-08-22 20:30 UTC, FlorGrosso commented on vda5050_msgs/msg/Factsheet.msg
> +int32 localization_parameters           # Detailed specification of localization
Sounds good, I agree.

2022-08-22 20:31 UTC, FlorGrosso commented on vda5050_msgs/CMakeLists.txt
> +    "msg/AGVGeometry.msg"
Sure

2022-08-22 21:05 UTC, FlorGrosso commented
Thanks @nwn-cpr ! All comments addressed and ready for another pass.

2022-08-23 15:27 UTC, nwn-cpr commented on vda5050_msgs/msg/AGVAction.msg
> +string[] action_scopes                          # Allowed scopes for using this action-type
I think the actionScope constants may have been lost here. I can't find them in the latest commit.

2022-08-23 15:30 UTC, nwn-cpr reviewed
Everything looks good except I think the actionScope constants were dropped.

2022-08-23 15:38 UTC, FlorGrosso commented on vda5050_msgs/msg/AGVAction.msg
> +string[] action_scopes                          # Allowed scopes for using this action-type
You're right! I've added them here. Thanks.

2022-08-23 15:42 UTC, nwn-cpr approved these changes
Thanks @FlorGrosso, this looks ready to merge.

2022-08-23 16:14 UTC, merged